import {
    BeforeInsert,
    CreateDateColumn,
    DeleteDateColumn,
    Entity,
    PrimaryColumn,
    UpdateDateColumn,
} from "typeorm";
import { v7 } from "uuid";

@Entity()
export class BaseEntity {
    @CreateDateColumn({
        name: "created_at",
        type: "timestamp",
    })
    createdAt!: Date;

    @DeleteDateColumn({
        name: "deleted_at",
        type: "timestamp",
    })
    deletedAt!: Date;

    @UpdateDateColumn({
        name: "updated_at",
        type: "timestamp",
    })
    updatedAt!: Date;
}

@Entity()
export class BaseEntityWithUUID extends BaseEntity {
    /**
     * UUIDv7 generated by uuid package
     * Also known as a timestamp-based UUID (allow sorting by creation time)
     * @see https://www.uuidgenerator.net/version7
     */
    @PrimaryColumn({
        name: "id",
        type: "uuid",
    })
    id!: string;

    @BeforeInsert()
    generateId() {
        if (!this.id) {
            this.id = v7();
        }
    }
}
